### PR TITLE
Eve savvy enhancements

### PR DESCRIPTION
**Pull request by aaronmallen**
* Add rubocop styling
* Add switch to methods for `Esi::Client`

### CODE REVIEW

**Comment by aaronmallen** [comment]
@dhiemstra this pull request is open but not ready for review, I am going through and implementing yardocs for all the public classes/methods I will ping you when this is actually ready for review. Can you do me a favor and at mention me when you merge #4 so that I can add it to this branch approriately.

**Comment by aaronmallen** [comment]
@dhiemstra actually lets go ahead and mark this PR as ready for review... there's a lot to document and I don't want documentation to hold up some of the other features introduced in this branch.

**Comment by aaronmallen** [comment]
I have created #9 to address finishing the documentation.

**Comment by aaronmallen** [comment]
@dhiemstra it might be better to get this reviewed and merged sooner than later to prevent new branches from generating new rubocop errors.

**Comment by dhiemstra** [comment]
This is great! Looks like you're just as OCD as I am regarding code styling ;)

**Pull request merged**
