### PR TITLE
Cache key set

### PR DESCRIPTION
**Pull request by dhiemstra**
@aaronmallen i tried to use `Set` as you proposed.

However, when fixing the test I found out every time I run the tests the cache key hash is different while the params from the set are static. For a cache key this doesn't seem useful I think 😊

I might do something wrong, can you have a look or just close this if you think the `params.sort` from #10 will do.

### CODE REVIEW

**Comment by aaronmallen** [comment]
@dhiemstra any chance one of the params is a datetime?

**Comment by dhiemstra** [comment]
No dynamic data at all, if you get a chance try to check this branch out and run the tests a few times

**Comment by aaronmallen** [comment]
Checkout #18

**Comment by aaronmallen** [comment]
@dhiemstra this should be merged #18 was merged into this branch

**Pull request merged**
